@startuml
participant ":InternTrackr" as IT
participant "c:StatusCommand" as SC
participant ":ApplicationList" as AL
participant "app:Application" as A
participant ":Ui" as UI
participant ":Storage" as S

[-> IT : executeCommand()
activate IT

IT -> SC : execute(applications, ui, storage)
activate SC

SC -> AL : getApplication(index)
activate AL
AL --> SC : app
deactivate AL

SC -> A : setStatus(newStatus)
activate A
deactivate A

SC -> UI : showMessage("Status updated!")
activate UI
UI --> SC
deactivate UI

SC -> S : save(applications)
activate S
S --> SC
deactivate S

deactivate SC
[<-- IT
deactivate IT
@enduml
