@startuml
hide footbox
participant ":FilterCommand" as FC
participant ":ApplicationList" as AL
participant "app:Application" as App
participant ":Ui" as UI

[-> FC : execute(applications, ui, storage)
activate FC

FC -> AL : getSize()
activate AL
AL --> FC : size
deactivate AL

loop for each application (1 to size)
    FC -> AL : getApplication(i)
    activate AL
    AL --> FC : app
    deactivate AL

    alt status matches searchStatus AND NOT isArchived
        FC -> UI : showMessage(app.toString())
        activate UI
        UI --> FC
        deactivate UI
    end
end
[<-- FC
deactivate FC
@enduml
